/**
 * @fileoverview Slash Command Permission Configuration Utility
 *
 * One-time utility script to configure Discord slash command permissions.
 * Sets which roles can execute specific commands in the guild.
 *
 * Usage:
 * 1. Run this script: node setPermissions.js
 * 2. Wait for "Connected" message
 * 3. Check Discord to verify command permissions are set
 * 4. Manually stop the script (Ctrl+C)
 *
 * What it does:
 * - Creates temporary Discord bot client
 * - Calls setCommandRoles() to configure permissions
 * - Uses babadata.guildId to target specific guild
 *
 * Note:
 * - This is a legacy utility script
 * - May be broken due to Discord API changes
 * - Command permissions are now typically set during deployment
 * - Consider using deployCommands.js instead
 *
 * @module setPermissions
 * @deprecated Discord API changes may have broken this functionality
 */

const { Client, Intents, Collection } = require('discord.js'); //discord module for interation with discord api
const Discord = require('discord.js'); //discord module for interation with discord api
var babadata = require('./babotdata.json'); //baba configuration file
const { setCommandRoles } = require('./HelperFunctions/adminHelpers.js');

const bot = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.DIRECT_MESSAGES], partials: ["CHANNEL"]});
bot.login(babadata.token); //login

bot.on('ready', function (evt)
{
	console.log('Connected');
	var gld = bot.guilds.cache.get(babadata.guildId);
	setCommandRoles(gld); // Configure command permissions for guild
});

//not shure what this does also but it was in jeremy's code so -- generated by Github Copilot

//stop the bot manually when you see all the commands as runnable (admins)

// WARNING: May be broken due to Discord API changes